import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#d7e5ec",
        "on-secondary-container": "#f2f3ff",
        "surface-bright": "#2e3b41",
        "inverse-surface": "#d7e5ec",
        "outline-variant": "#3b4a3d",
        "on-error": "#690005",
        "surface-container-highest": "#2a373c",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#bacbb9",
        "on-secondary": "#002d6e",
        "primary-container": "#00e676",
        "on-tertiary-fixed": "#400009",
        "secondary-fixed": "#d9e2ff",
        "on-primary-fixed-variant": "#005226",
        "on-tertiary-fixed-variant": "#920021",
        "on-background": "#d7e5ec",
        "secondary-fixed-dim": "#b0c6ff",
        "tertiary": "#ffdddc",
        "primary": "#75ff9e",
        "on-secondary-fixed-variant": "#00429b",
        "on-tertiary-container": "#ab0028",
        "surface": "#08151a",
        "tertiary-fixed-dim": "#ffb3b3",
        "on-primary-container": "#00612e",
        "surface-tint": "#00e475",
        "outline": "#859585",
        "inverse-on-surface": "#253238",
        "background": "#08151a",
        "inverse-primary": "#006d35",
        "on-primary-fixed": "#00210b",
        "on-primary": "#003918",
        "tertiary-container": "#ffb6b6",
        "on-secondary-fixed": "#001945",
        "secondary": "#b0c6ff",
        "surface-container-high": "#1f2c31",
        "error": "#ffb4ab",
        "surface-variant": "#2a373c",
        "surface-container-low": "#101d23",
        "primary-fixed": "#62ff96",
        "tertiary-fixed": "#ffdad9",
        "on-tertiary": "#680014",
        "secondary-container": "#0068ed",
        "error-container": "#93000a",
        "surface-container-lowest": "#041015",
        "primary-fixed-dim": "#00e475",
        "surface-container": "#142127",
        "surface-dim": "#08151a",
        app: {
          bg: "var(--bg)",
          surface: "var(--surface)",
          elevated: "var(--surface-elevated)",
          sunken: "var(--surface-sunken)",
          border: "var(--border)",
          "border-strong": "var(--border-strong)",
          muted: "var(--muted)",
          "muted-strong": "var(--muted-strong)",
          text: "var(--text)",
          "text-soft": "var(--text-soft)",
          primary: "var(--primary)",
          "primary-soft": "var(--primary-soft)",
          "primary-softer": "var(--primary-softer)",
          "primary-strong": "var(--primary-strong)",
          cyan: "var(--cyan)",
          blue: "var(--blue)",
          emerald: "var(--emerald)",
          amber: "var(--amber)",
          rose: "var(--rose)",
          purple: "var(--purple)",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Plus Jakarta Sans", "Inter", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
        display: ["JetBrains Mono", "monospace"],
        body: ["Inter", "sans-serif"],
      },
      boxShadow: {
        "panel-card":
          "0 1px 1px rgba(15,23,42,0.025), 0 8px 22px -14px rgba(15,23,42,0.12)",
        "soft-pop":
          "0 1px 2px rgba(15,23,42,0.04), 0 6px 18px -8px rgba(15,23,42,0.12)",
      },
      keyframes: {
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.25" },
        },
        "soft-pulse": {
          "0%, 100%": { transform: "scale(1)", opacity: "0.7" },
          "50%": { transform: "scale(1.4)", opacity: "0" },
        },
      },
      animation: {
        blink: "blink 1.4s ease-in-out infinite",
        "soft-pulse": "soft-pulse 1.8s ease-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
