/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current plant and market state */
        get: operations["getCurrentState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecasts/{variable}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast series by variable */
        get: operations["getForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current optimized allocation plan */
        get: operations["getCurrentPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan/{plan_id}/explain/{hour_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explain one hour of a plan */
        get: operations["explainPlanHour"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a scenario with operator overrides */
        post: operations["runScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constraints/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current safety and regulatory constraint status */
        get: operations["getConstraintsStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent optimizer runs */
        get: operations["getHistoryRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mock/scenario/{scenario_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load a predefined demo scenario */
        get: operations["getMockScenario"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok";
            /** @example 0.1.0 */
            version: string;
            /**
             * Format: date-time
             * @example 2026-05-14T12:00:00Z
             */
            timestamp: string;
        };
        Reactor: {
            /** @example paks-1 */
            id: string;
            /** @example VVER-440 */
            type: string;
            /** @example 1485 */
            thermal_mw: number;
            /** @example 500 */
            electric_mw: number;
            /**
             * @example online
             * @enum {string}
             */
            status: "online" | "offline" | "maintenance" | "limited";
        };
        CurrentStateResponse: {
            reactors: components["schemas"]["Reactor"][];
            prices: {
                /** @example -18 */
                current_eur_mwh: number;
                /** @example -12 */
                next_hour: number;
            };
            danube: {
                /** @example 26.3 */
                temperature_c: number;
                /** @example 2400 */
                flow_m3s: number;
            };
            heat_demand: {
                /** @example 80 */
                paks_mw: number;
                /** @example 95 */
                szekszard_mw: number;
                /** @example 185 */
                dunaujvaros_mw: number;
            };
            /**
             * Format: date-time
             * @example 2026-05-14T12:00:00Z
             */
            timestamp: string;
        };
        /** @enum {string} */
        ForecastVariable: "electricity_price" | "danube_temp" | "heat_demand_paks" | "heat_demand_szekszard" | "heat_demand_dunaujvaros";
        ForecastPoint: {
            /**
             * Format: date-time
             * @example 2026-05-14T12:00:00Z
             */
            timestamp: string;
            /** @example -18 */
            value: number;
            /** @example -24 */
            lower_bound: number;
            /** @example -9 */
            upper_bound: number;
        };
        ForecastResponse: {
            /** @example electricity_price */
            variable: string;
            /** @example 48 */
            horizon_hours: number;
            points: components["schemas"]["ForecastPoint"][];
            /** @example forecast-baseline-0.1.0 */
            model_version: string;
        };
        Allocation: {
            /** @example 620 */
            p_elec_to_grid_mw: number;
            /** @example 80 */
            p_heat_paks_mw: number;
            /** @example 95 */
            p_heat_szekszard_mw: number;
            /** @example 185 */
            p_heat_dunaujvaros_mw: number;
            /** @example 360 */
            p_h2_elec_mw: number;
            /** @example 140 */
            p_danube_mw: number;
        };
        MarginalRevenue: {
            /** @example -18 */
            electricity: number;
            /** @example 42 */
            heat: number;
            /** @example 58 */
            hydrogen: number;
            /** @example 0 */
            danube: number;
        };
        PerReactorAllocation: {
            /** @example paks-1 */
            reactor_id: string;
            allocation: components["schemas"]["Allocation"];
        };
        PlanHour: {
            /** @example 14 */
            hour_index: number;
            /**
             * Format: date-time
             * @example 2026-05-14T14:00:00Z
             */
            timestamp: string;
            allocation: components["schemas"]["Allocation"];
            per_reactor: components["schemas"]["PerReactorAllocation"][];
            /**
             * @example [
             *       "hydrogen_capacity",
             *       "negative_electricity_price"
             *     ]
             */
            binding_constraints: string[];
            marginal_revenue: components["schemas"]["MarginalRevenue"];
            /** @example 32000 */
            expected_revenue_eur: number;
        };
        PlanResponse: {
            /**
             * Format: uuid
             * @example 3f6e6d8e-9d55-4a2c-9f3f-37d9bc1e1f4a
             */
            plan_id: string;
            /**
             * Format: date-time
             * @example 2026-05-14T12:00:00Z
             */
            generated_at: string;
            /** @example 48 */
            horizon_hours: number;
            hours: components["schemas"]["PlanHour"][];
            /** @example 3200000 */
            total_revenue_eur: number;
            /**
             * @example optimal
             * @enum {string}
             */
            solver_status: "optimal" | "fallback_greedy" | "fallback_safe";
        };
        ConstraintExplanation: {
            /** @example Danube temperature */
            name: string;
            /** @example 26.3 */
            value: number;
            /** @example 30 */
            limit: number;
            /** @example 3.7 */
            margin: number;
            /** @example C */
            units: string;
            /** @example River temperature is below the regulatory limit. */
            description: string;
        };
        ExplainResponse: {
            /** @example 14 */
            hour_index: number;
            allocation: components["schemas"]["Allocation"];
            marginal_revenue_per_mw: components["schemas"]["MarginalRevenue"];
            binding_constraints: components["schemas"]["ConstraintExplanation"][];
            slack_constraints: components["schemas"]["ConstraintExplanation"][];
            comparison_to_baseline: {
                /** @example full_electricity_output */
                baseline_action: string;
                /** @example 12600 */
                baseline_revenue_eur: number;
                /** @example 32000 */
                optimized_revenue_eur: number;
                /** @example 19400 */
                improvement_eur: number;
            };
        };
        ScenarioRequest: {
            overrides?: {
                /** @example 0.8 */
                price_multiplier?: number;
                /** @example 30 */
                danube_temp_limit?: number;
                /** @example 1.1 */
                demand_multiplier?: number;
                /**
                 * @example [
                 *       "paks-3"
                 *     ]
                 */
                reactor_offline?: string[];
            };
            /** @example 48 */
            horizon_hours?: number;
        };
        ConstraintStatus: {
            /** @example Danube temperature */
            name: string;
            /** @example Maximum allowed river outlet temperature. */
            description: string;
            /** @example demo_safety_policy */
            regulatory_source: string;
            /** @example 26.3 */
            current_value: number;
            /** @example 30 */
            limit_value: number;
            /** @example 3.7 */
            safety_margin: number;
            /** @example C */
            units: string;
            /**
             * @example warning
             * @enum {string}
             */
            status: "safe" | "warning" | "violation";
        };
        ConstraintsStatusResponse: {
            constraints: components["schemas"]["ConstraintStatus"][];
        };
        HistoryRun: {
            /** @example run-20260514-120000 */
            run_id: string;
            /**
             * Format: date-time
             * @example 2026-05-14T12:00:00Z
             */
            started_at: string;
            /** @example optimal */
            solver_status: string;
            /** @example 3200000 */
            objective_value: number;
            /** @example 420 */
            solve_time_ms: number;
            /** @example none */
            fallback_level: string;
        };
        HistoryRunsResponse: {
            runs: components["schemas"]["HistoryRun"][];
        };
        /** @enum {string} */
        ScenarioName: "summer_negative_price" | "winter_peak_demand" | "danube_overheating";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getCurrentState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current state snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentStateResponse"];
                };
            };
        };
    };
    getForecast: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variable: components["schemas"]["ForecastVariable"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forecast points for the selected variable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
        };
    };
    getCurrentPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current plan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
        };
    };
    explainPlanHour: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
                hour_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hour-level optimization explanation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
        };
    };
    runScenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Scenario optimized plan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
        };
    };
    getConstraintsStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Constraint status list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstraintsStatusResponse"];
                };
            };
        };
    };
    getHistoryRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent optimizer run history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryRunsResponse"];
                };
            };
        };
    };
    getMockScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_name: components["schemas"]["ScenarioName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mock scenario optimized plan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
        };
    };
}
